#!/usr/bin/env python3
"""Reproducible Gaussian window-sensitivity test for original 1651050 CAL pixels.

This is an independent SIX-parameter elliptical Gaussian + flat background
fit of the exact SCI/ERR/DQ stamps generated by inspect_1651050_f356w.py.
It does not use the archived Gaussian centroid as a truth label; it only uses
that centroid as the initial optimizer seed when available.
No rejected image is upgraded to a secure astrometric detection.
"""
from __future__ import annotations
import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.optimize import least_squares

WINDOW_HALFSIZES=(3,4,5,6,7)
BAD_DQ_MASK=1|2|4|16


def fit_once(stamp,half):
    sci=np.asarray(stamp["SCI"],dtype=float)
    err=np.asarray(stamp["ERR"],dtype=float)
    dq=np.asarray(stamp["DQ"],dtype=np.uint64)
    tx=float(stamp["catalog_x_local"])-float(stamp["pixel_window_x0"])
    ty=float(stamp["catalog_y_local"])-float(stamp["pixel_window_y0"])
    bx=float(stamp["gaussian_x_local"])-float(stamp["pixel_window_x0"])
    by=float(stamp["gaussian_y_local"])-float(stamp["pixel_window_y0"])
    Y,X=np.indices(sci.shape)
    mask=(abs(X-tx)<=half)&(abs(Y-ty)<=half)&np.isfinite(sci)&np.isfinite(err)&(err>0)&((dq&BAD_DQ_MASK)==0)
    x=X[mask];y=Y[mask];a=sci[mask];e=err[mask]
    if len(a)<20:raise ValueError("Fewer than 20 nonflagged pixels")
    outer=((X-tx)**2+(Y-ty)**2>60)&np.isfinite(sci)
    bg=float(np.nanmedian(sci[outer]))
    amplitude=max(float(np.nanmax(a)-bg),1e-4)
    cx,cy=(bx,by) if np.isfinite([bx,by]).all() else (tx,ty)
    low=np.array([0,tx-2.5,ty-2.5,0.6,0.6,-np.inf])
    high=np.array([np.inf,tx+2.5,ty+2.5,1.6,1.6,np.inf])
    p=np.array([amplitude,np.clip(cx,low[1]+.01,high[1]-.01),
                np.clip(cy,low[2]+.01,high[2]-.01),.85,.85,bg])
    def pred(q):return q[0]*np.exp(-.5*((x-q[1])/q[3])**2-.5*((y-q[2])/q[4])**2)+q[5]
    res=least_squares(lambda q:(pred(q)-a)/e,p,bounds=(low,high),loss="linear",max_nfev=1000)
    q=res.x
    hit_boundary=any((abs(q[i]-low[i])<.025 or abs(q[i]-high[i])<.025) for i in (1,2,3,4))
    return {
        "window_pixels":2*half+1,"center_x_local":float(q[1]),
        "center_y_local":float(q[2]),
        "x_minus_catalog_pix":float(q[1]-tx),
        "y_minus_catalog_pix":float(q[2]-ty),
        "relative_to_original_gauss_pix":float(np.hypot(q[1]-bx,q[2]-by))
                          if np.isfinite([bx,by]).all() else np.nan,
        "sigma_x_pix":float(q[3]),"sigma_y_pix":float(q[4]),
        "amplitude":float(q[0]),
        "reduced_chi2":float(np.sum(((pred(q)-a)/e)**2)/max(1,len(a)-6)),
        "n_unmasked_pixels":int(len(a)),
        "optimizer_success":bool(res.success),"fit_at_bound":bool(hit_boundary)
    }


def summarize_f356w(rows):
    target=rows[
      rows.filename.str.contains("jw05893016008_05101_00001_nrcblong")
    ].copy()
    if len(target)!=len(WINDOW_HALFSIZES):raise RuntimeError("Missing accepted F356W fit")
    if target.fit_at_bound.any():raise RuntimeError("Accepted F356W fit hit optimizer boundary")
    dx=float(target.center_x_local.max()-target.center_x_local.min())
    dy=float(target.center_y_local.max()-target.center_y_local.min())
    return dx,dy,float(np.hypot(dx,dy))


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--input",type=Path,default=Path("input_cal_qa/pixel_stamps"))
    ap.add_argument("--output",type=Path,default=Path("publication_check/window_robustness"))
    args=ap.parse_args()
    files=sorted(args.input.glob("*.npz"))
    if len(files)!=6:
        raise RuntimeError(f"Expected six independently downloaded CAL pixel stamps; found {len(files)}")
    args.output.mkdir(parents=True,exist_ok=True)
    results=[]
    for file in files:
        with np.load(file,allow_pickle=False) as z:
            for half in WINDOW_HALFSIZES:
                row=fit_once(z,half)
                results.append({"filename":file.name,"filter":str(z["filter"]),**row})
    df=pd.DataFrame(results)
    df.to_csv(args.output/"gaussian_window_sensitivity.csv",index=False)
    dx,dy,dvec=summarize_f356w(df)
    target=df[df.filename.str.contains("jw05893016008_05101_00001_nrcblong")]
    fig,ax=plt.subplots(figsize=(7,5))
    ax.plot(target.window_pixels,target.x_minus_catalog_pix,"o-",label="Gaussian x (detector pixel)")
    ax.plot(target.window_pixels,target.y_minus_catalog_pix,"s-",label="Gaussian y (detector pixel)")
    ax.set_xlabel("Fitting window width (pixels)")
    ax.set_ylabel("Fitted centroid minus catalog gWCS (pixels)")
    ax.set_title("Candidate 1651050: accepted F356W centroid vs window size")
    ax.legend();ax.grid(alpha=.25);fig.tight_layout()
    fig.savefig(args.output/"accepted_F356W_window_stability.png",dpi=180)
    plt.close(fig)
    report=[
        "# Independent Gaussian fit sensitivity to fitting window",
        "",
        "This is a re-fit of the original Stage-2 CAL image stamp using a six-parameter elliptical Gaussian plus flat background, with ERR-weighted residuals and original DQ masking. Pixel coordinates are **detector pixels**, not sky-registered positions.",
        "",
        f"Accepted F356W: fitting windows 7, 9, 11, 13 and 15 pixels produce fitted centroid span Δx={dx:.4f} and Δy={dy:.4f} pixels; combined envelope {dvec:.4f} pixels (~{dvec*63.46:.2f} mas at 63.46 mas/pixel).",
        "This is stability **within the same exposure** against the chosen window; it is not the absolute centroid accuracy.",
        "",
        "The original accepted F356W Gaussian-COM separation is 2.18 pixels (~138 mas). Such a wide center-of-mass displacement is expected if the larger COM window is pulled by neighboring flux, but that explanation must be visually judged from SCI/ERR/DQ.",
        "",
        "**Caution:** other F356W exposures were rejected by the original astrometric pipeline. The exploratory Gaussian fits here must not be interpreted as recovered statistically independent PM detections, particularly if an optimizer parameter is at its bound or target DQ is questionable.",
        "",
        "No PSF/ePSF or JWST-specific parallax fit is performed here. The classification of the candidate is unchanged.",
    ]
    (args.output/"RESULTS_README.md").write_text("\n".join(report)+"\n")
    print("\n".join(report))


if __name__=="__main__":main()
