# Conservative defaults for exhaustive PM search.
MIN_BASELINE_DAYS = 30.0
EPOCH_GAP_DAYS = 1.0
ASSOCIATION_RADIUS_PIX = 4.0
ASTROM_BAD_BITS = 1 | 2 | 4 | 16
TARGET_MIN_SNR = 3.0
CONTROL_MIN_SNR = 10.0
MIN_CONTROL_MATCHES = 6
MOVING_SIGMA = 5.0
ZERO_SIGMA = 3.0
MAX_STATIONARY_SIGMA_MASYR = 20.0
